services:
  - type: web
    name: profhub
    env: docker
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JDBC_DATABASE_DRIVER
        value: org.postgresql.Driver
      - key: HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: H2_CONSOLE_ENABLED
        value: false 